version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.routing.allocation.disk.watermark.low=2gb
      - cluster.routing.allocation.disk.watermark.high=1gb
      - cluster.routing.allocation.disk.watermark.flood_stage=512mb
      - cluster.info.update.interval=1m

    ports:
      - 9200:9200
    volumes:
      - type: bind
        source: /mnt/victor2/elasticsearch_data
        target: /usr/share/elasticsearch/data
        bind:
          propagation: rshared
